theme: jekyll-theme-minimal
title: Web Development with JavaScript - Training
description: Training page of Web Development with JavaScript
show_downloads: false
author: 'Chitra K'
subtitle: 'RVS College of Arts and Science'
github:
  is_project_page: false